# Generated by Django 5.2.8 on 2025-11-07 07:26

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'saved_posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('category', models.CharField(choices=[('food', 'Food & Restaurants'), ('fashion', 'Fashion & Clothing'), ('books', 'Books & Education'), ('health', 'Health & Wellness'), ('education', 'Education & Training'), ('services', 'Services'), ('electronics', 'Electronics'), ('home', 'Home & Garden'), ('beauty', 'Beauty & Personal Care'), ('sports', 'Sports & Fitness')], max_length=100)),
                ('image_url', models.URLField(max_length=500)),
                ('image_thumbnail', models.URLField(blank=True, max_length=500, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('total_likes', models.IntegerField(default=0)),
                ('total_inquiries', models.IntegerField(default=0)),
                ('total_views', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('auto_share_instagram', models.BooleanField(default=False)),
                ('auto_share_facebook', models.BooleanField(default=False)),
                ('shared_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='businesses.business')),
            ],
            options={
                'db_table': 'posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostDailyLimit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('posts_count', models.IntegerField(default=0)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_limits', to='businesses.business')),
            ],
            options={
                'db_table': 'post_daily_limits',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='posts.post')),
            ],
            options={
                'db_table': 'post_likes',
                'ordering': ['-created_at'],
            },
        ),
    ]
