# Generated by Django 5.2.8 on 2025-12-03 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0002_initial'),
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='post',
            name='product_category',
            field=models.ForeignKey(blank=True, help_text='Specific product category created by business', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.productcategory'),
        ),
        migrations.AddField(
            model_name='savedpost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='posts.post'),
        ),
        migrations.AddField(
            model_name='savedpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='postdailylimit',
            unique_together={('business', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together={('post', 'user')},
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['business', 'is_active'], name='product_cat_busines_6e8f57_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('business', 'slug')},
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['business_category', '-created_at'], name='posts_busines_3ddd0a_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['product_category', '-created_at'], name='posts_product_cd5938_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_featured', '-created_at'], name='posts_is_feat_2fc698_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['business', 'product_category', '-created_at'], name='posts_busines_d48397_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedpost',
            unique_together={('post', 'user')},
        ),
    ]
