# Generated by Django 5.2.8 on 2025-11-23 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_thumbnail',
        ),
    ]
