# Generated by Django 5.2.8 on 2025-11-29 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0007_alter_businesscategory_slug'),
        ('posts', '0003_remove_post_image_thumbnail'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='post',
            new_name='posts_categor_4138d2_idx',
            old_name='posts_categor_b285e2_idx',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='businesses.businesscategory'),
        ),
    ]
