# Generated by Django 5.2.8 on 2026-04-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Opsional. Mund të përdoret për login.', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('user_type', 'business'), _negated=True), ('email__isnull', False), ('phone__isnull', False), _connector='OR'), name='business_requires_email_or_phone'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('email__isnull', False), ('username__isnull', False), _connector='OR'), name='user_requires_email_or_username'),
        ),
    ]
