# Generated by Django 5.2.8 on 2026-04-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_username_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
