# Generated by Django 5.2.8 on 2025-11-07 07:26

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('food', 'Food & Restaurants'), ('fashion', 'Fashion & Clothing'), ('books', 'Books & Education'), ('health', 'Health & Wellness'), ('education', 'Education & Training'), ('services', 'Services'), ('electronics', 'Electronics'), ('home', 'Home & Garden'), ('beauty', 'Beauty & Personal Care'), ('sports', 'Sports & Fitness')], max_length=100)),
                ('logo', models.URLField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default='Albania', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('business_hours', models.JSONField(blank=True, null=True)),
                ('is_open_now', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_documents', models.JSONField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('premium_until', models.DateTimeField(blank=True, null=True)),
                ('max_posts_per_day', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)])),
                ('total_followers', models.IntegerField(default=0)),
                ('total_subscribers', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_reviews', models.IntegerField(default=0)),
                ('is_halal_certified', models.BooleanField(default=False)),
                ('halal_certificate', models.URLField(blank=True, max_length=500, null=True)),
                ('social_instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('social_facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Businesses',
                'db_table': 'businesses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('profile_views', models.IntegerField(default=0)),
                ('post_views', models.IntegerField(default=0)),
                ('total_clicks', models.IntegerField(default=0)),
                ('total_inquiries', models.IntegerField(default=0)),
                ('total_followers_gained', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'business_analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'followers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'subscribers',
                'ordering': ['-created_at'],
            },
        ),
    ]
