# Generated by Django 5.2.8 on 2025-12-03 17:10

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('logo', models.URLField(blank=True, max_length=500, null=True)),
                ('logo_public_id', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('country', models.CharField(default='Albania', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('business_hours', models.JSONField(blank=True, null=True)),
                ('is_open_now', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('verification_documents', models.JSONField(blank=True, null=True)),
                ('verification_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('is_premium', models.BooleanField(db_index=True, default=False)),
                ('premium_until', models.DateTimeField(blank=True, null=True)),
                ('max_posts_per_day', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)])),
                ('total_followers', models.IntegerField(default=0)),
                ('total_subscribers', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_reviews', models.IntegerField(default=0)),
                ('is_halal_certified', models.BooleanField(db_index=True, default=False)),
                ('halal_certificate', models.URLField(blank=True, max_length=500, null=True)),
                ('halal_certificate_public_id', models.CharField(blank=True, max_length=255, null=True)),
                ('social_instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('social_facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Businesses',
                'db_table': 'businesses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('profile_views', models.IntegerField(default=0)),
                ('post_views', models.IntegerField(default=0)),
                ('total_clicks', models.IntegerField(default=0)),
                ('total_inquiries', models.IntegerField(default=0)),
                ('total_followers_gained', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'business_analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('icon', models.CharField(blank=True, choices=[('restaurant_rounded', 'Restaurant'), ('local_cafe_rounded', 'Cafe'), ('bakery_dining_rounded', 'Bakery'), ('local_pizza_rounded', 'Pizza'), ('lunch_dining_rounded', 'Fast Food'), ('ramen_dining_rounded', 'Ramen/Noodles'), ('store_rounded', 'Store/Market'), ('storefront_rounded', 'Shop/Butcher'), ('checkroom_rounded', 'Clothing Store'), ('shopping_bag_rounded', 'Shopping'), ('shopping_cart_rounded', 'Supermarket'), ('content_cut_rounded', 'Barbershop'), ('face_rounded', 'Beauty/Salon'), ('spa_rounded', 'Spa'), ('cleaning_services_rounded', 'Cleaning'), ('build_rounded', 'Construction/Repair'), ('plumbing_rounded', 'Plumbing'), ('electrical_services_rounded', 'Electrical'), ('local_hospital_rounded', 'Hospital/Clinic'), ('local_pharmacy_rounded', 'Pharmacy'), ('medical_services_rounded', 'Medical Services'), ('dental_services_rounded', 'Dental'), ('psychology_rounded', 'Psychology'), ('school_rounded', 'School/Education'), ('mosque_rounded', 'Mosque'), ('menu_book_rounded', 'Library/Books'), ('science_rounded', 'Science/Lab'), ('flight_rounded', 'Travel Agency'), ('hotel_rounded', 'Hotel'), ('apartment_rounded', 'Apartment/Real Estate'), ('directions_car_rounded', 'Car Services'), ('local_taxi_rounded', 'Taxi'), ('fitness_center_rounded', 'Gym/Fitness'), ('sports_soccer_rounded', 'Sports'), ('pool_rounded', 'Swimming'), ('computer_rounded', 'Computer/Tech'), ('phone_android_rounded', 'Mobile/Electronics'), ('camera_rounded', 'Photography'), ('movie_rounded', 'Cinema/Entertainment'), ('theater_comedy_rounded', 'Theater'), ('music_note_rounded', 'Music'), ('business_rounded', 'Default Business'), ('business_center_rounded', 'Business Center'), ('store_mall_directory_rounded', 'Mall/Directory')], default='business_rounded', help_text='Material Icon name for Flutter app', max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business Category',
                'verbose_name_plural': 'Business Categories',
                'db_table': 'business_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'followers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'subscribers',
                'ordering': ['-created_at'],
            },
        ),
    ]
