# Generated by Django 5.2.8 on 2025-11-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_populate_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscategory',
            name='icon',
            field=models.CharField(blank=True, choices=[('restaurant_rounded', 'Restaurant'), ('local_cafe_rounded', 'Cafe'), ('bakery_dining_rounded', 'Bakery'), ('local_pizza_rounded', 'Pizza'), ('lunch_dining_rounded', 'Fast Food'), ('ramen_dining_rounded', 'Ramen/Noodles'), ('store_rounded', 'Store/Market'), ('storefront_rounded', 'Shop/Butcher'), ('checkroom_rounded', 'Clothing Store'), ('shopping_bag_rounded', 'Shopping'), ('shopping_cart_rounded', 'Supermarket'), ('content_cut_rounded', 'Barbershop'), ('face_rounded', 'Beauty/Salon'), ('spa_rounded', 'Spa'), ('cleaning_services_rounded', 'Cleaning'), ('build_rounded', 'Construction/Repair'), ('plumbing_rounded', 'Plumbing'), ('electrical_services_rounded', 'Electrical'), ('local_hospital_rounded', 'Hospital/Clinic'), ('local_pharmacy_rounded', 'Pharmacy'), ('medical_services_rounded', 'Medical Services'), ('dental_services_rounded', 'Dental'), ('psychology_rounded', 'Psychology'), ('school_rounded', 'School/Education'), ('mosque_rounded', 'Mosque'), ('menu_book_rounded', 'Library/Books'), ('science_rounded', 'Science/Lab'), ('flight_rounded', 'Travel Agency'), ('hotel_rounded', 'Hotel'), ('apartment_rounded', 'Apartment/Real Estate'), ('directions_car_rounded', 'Car Services'), ('local_taxi_rounded', 'Taxi'), ('fitness_center_rounded', 'Gym/Fitness'), ('sports_soccer_rounded', 'Sports'), ('pool_rounded', 'Swimming'), ('computer_rounded', 'Computer/Tech'), ('phone_android_rounded', 'Mobile/Electronics'), ('camera_rounded', 'Photography'), ('movie_rounded', 'Cinema/Entertainment'), ('theater_comedy_rounded', 'Theater'), ('music_note_rounded', 'Music'), ('business_rounded', 'Default Business'), ('business_center_rounded', 'Business Center'), ('store_mall_directory_rounded', 'Mall/Directory')], default='business_rounded', help_text='Material Icon name for Flutter app', max_length=50, null=True),
        ),
    ]
