# Generated by Django 5.2.8 on 2025-11-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_business_website_alter_business_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscategory',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
