# Generated by Django 5.2.8 on 2025-11-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0007_alter_businesscategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='halal_certificate_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='logo_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
