# Generated by Django 5.2.8 on 2025-11-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0008_business_halal_certificate_public_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='city',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='is_halal_certified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='business',
            name='is_premium',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='business',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
