# Generated by Django 5.2.8 on 2025-11-07 07:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('inquiry', 'Inquiry Received'), ('review', 'Review Added'), ('follow', 'New Follower'), ('subscribe', 'New Subscriber'), ('admin', 'Admin Message'), ('group', 'Group Activity'), ('message', 'New Message')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('related_type', models.CharField(blank=True, max_length=50, null=True)),
                ('related_id', models.UUIDField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
